import fs from 'fs';
import path from 'path';

const TEMPLATES_DIR = path.join(import.meta.dirname, '..', 'src', 'remotion', 'templates');
const GENERATED_DIR = path.join(import.meta.dirname, '..', 'src', 'remotion', 'generated');

interface DataOption {
  key: string;
  label: string;
  type: 'text' | 'number' | 'select';
  default?: unknown;
  required?: boolean;
  min?: number;
  max?: number;
  options?: {value: string; label: string}[];
}

interface TemplateMeta {
  id: string;
  name: string;
  description: string;
  componentId: string;
  width: number;
  height: number;
  fps: number;
  defaultDuration: number;
  dataOptions: DataOption[];
}

function discoverTemplates(): TemplateMeta[] {
  const entries = fs.readdirSync(TEMPLATES_DIR, {withFileTypes: true});
  const templates: TemplateMeta[] = [];

  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const metaPath = path.join(TEMPLATES_DIR, entry.name, 'meta.json');
    if (!fs.existsSync(metaPath)) continue;

    const raw = fs.readFileSync(metaPath, 'utf-8');
    const meta = JSON.parse(raw) as TemplateMeta;

    // Validate required fields
    if (!meta.id || !meta.componentId) {
      console.warn(`[build-templates] Skipping ${entry.name}: missing id or componentId`);
      continue;
    }

    templates.push(meta);
  }

  return templates.sort((a, b) => a.name.localeCompare(b.name));
}

function generateRegistry(templates: TemplateMeta[]): string {
  const imports = templates
    .map((t) => `import type {${capitalize(camelCase(t.id))}Props} from '../templates/${t.id}';`)
    .join('\n');

  const entries = templates
    .map(
      (t) =>
        `  '${t.id}': {
    meta: ${JSON.stringify(t, null, 6).replace(/^/gm, '    ').trim()} as const,
    componentId: '${t.componentId}' as const,
  },`,
    )
    .join('\n');

  return `// AUTO-GENERATED by scripts/build-templates.ts — do not edit manually
${imports}

export type TemplateId = ${templates.map((t) => `'${t.id}'`).join(' | ')};

export type TemplatePropsMap = {
${templates.map((t) => `  '${t.id}': ${capitalize(camelCase(t.id))}Props;`).join('\n')}
};

export interface TemplateEntry {
  meta: TemplateMeta;
  componentId: string;
}

export interface TemplateMeta {
  id: string;
  name: string;
  description: string;
  componentId: string;
  width: number;
  height: number;
  fps: number;
  defaultDuration: number;
  dataOptions: DataOption[];
}

export interface DataOption {
  key: string;
  label: string;
  type: 'text' | 'number' | 'select';
  default?: unknown;
  required?: boolean;
  min?: number;
  max?: number;
  options?: {value: string; label: string}[];
}

export const TEMPLATES: Record<TemplateId, TemplateEntry> = {
${entries}
};

export function getTemplate(id: string): TemplateEntry | undefined {
  return TEMPLATES[id as TemplateId];
}

export function getAllTemplates(): TemplateEntry[] {
  return Object.values(TEMPLATES);
}
`;
}

function generateRoot(templates: TemplateMeta[]): string {
  const imports = templates
    .map(
      (t) =>
        `const ${capitalize(camelCase(t.id))} = React.lazy(() =>\n  import('../templates/${t.id}').then((m) => ({default: m.${capitalize(camelCase(t.id))}})),\n);`,
    )
    .join('\n');

  const compositions = templates
    .map(
      (t) =>
        `      <Composition
        id="${t.componentId}"
        component={${capitalize(camelCase(t.id))}}
        durationInFrames={${t.fps} * ${t.defaultDuration}}
        fps={${t.fps}}
        width={${t.width}}
        height={${t.height}}
        defaultProps={{} as any}
      />`,
    )
    .join('\n');

  return `// AUTO-GENERATED by scripts/build-templates.ts — do not edit manually
/* eslint-disable @typescript-eslint/no-explicit-any */
import React from 'react';
import {Composition} from 'remotion';

${imports}

export const RemotionRoot: React.FC = () => {
  return (
    <>
${compositions}
    </>
  );
};
`;
}

function generateSchema(templates: TemplateMeta[]): string {
  // Build a simple validation object (Zod is available but we keep it lightweight)
  const templateIds = templates.map((t) => `'${t.componentId}'`).join(' | ');

  return `// AUTO-GENERATED by scripts/build-templates.ts — do not edit manually

export const COMP_IDS = [${templates.map((t) => `'${t.componentId}'`).join(', ')}] as const;

export type CompId = (typeof COMP_IDS)[number];

export function isValidCompId(id: string): id is CompId {
  return (COMP_IDS as readonly string[]).includes(id);
}
`;
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function camelCase(s: string): string {
  return s
    .split('-')
    .map((part) => capitalize(part))
    .join('');
}

// Main
const templates = discoverTemplates();
console.log(`[build-templates] Found ${templates.length} templates:`);
for (const t of templates) {
  console.log(`  - ${t.id} (${t.componentId})`);
}

fs.mkdirSync(GENERATED_DIR, {recursive: true});

const registry = generateRegistry(templates);
fs.writeFileSync(path.join(GENERATED_DIR, 'registry.ts'), registry);
console.log(`[build-templates] Wrote generated/registry.ts`);

const root = generateRoot(templates);
fs.writeFileSync(path.join(GENERATED_DIR, 'Root.tsx'), root);
console.log(`[build-templates] Wrote generated/Root.tsx`);

const schema = generateSchema(templates);
fs.writeFileSync(path.join(GENERATED_DIR, 'schema.ts'), schema);
console.log(`[build-templates] Wrote generated/schema.ts`);

console.log(`[build-templates] Done`);
